CC = g++

EXE1 = DS081
EXE2 = DS082
EXE3 = DS083
EXE4 = DS084

EXEALL = $(EXE1) $(EXE2) $(EXE3) $(EXE4)

all: $(EXEALL)

$(EXE1): $(EXE1).cpp
	$(CC) -o $@ $^

$(EXE2): $(EXE2).cpp
	$(CC) -o $@ $^

$(EXE3): $(EXE3).cpp
	$(CC) -o $@ $^

$(EXE4): $(EXE4).cpp
	$(CC) -o $@ $^

clean:
	del $(EXE1).exe
	del $(EXE2).exe
	del $(EXE3).exe
	del $(EXE4).exe


